# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Doc link: https://docs.vagrantup.com.

  # Use Debian 8 as base image.
  config.vm.box = "ubuntu/bionic64"

  # hostname of this VM
  config.vm.hostname = "neo"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # name of the vm
    vb.name = "neo"

    # resouce allocations.
    vb.memory = "3072"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo 'APT::Install-Suggests "0";' > /mac_config/apt/apt.conf.d/01xiaomo &&
    echo 'APT::Install-Recommends "0";' >> /mac_config/apt/apt.conf.d/01xiaomo &&
    apt update &&
    apt purge -y command-not-found command-not-found-data ftp ntfs-3g vim* &&
    apt upgrade -y &&
    apt install -y python3-pip neovim lftp python3-setuptools golang procmail &&
    pip3 install -U pip &&
    pip install requests pipenv black neovim icdiff ptpython sh
    timedatectl set-timezone Australia/Melbourne
    echo "Done with System setup."
  SHELL

  $user_script = <<-SCRIPT
    mkdir -p ~/.config/ ~/.xiaomo/var/{log,run,tmp} ~/.xiaomo/share/github &&
    cd ~/.xiaomo/share/github &&
    if [ ! -d ~/.xiaomo/share/github/mac_config ]
    then
      git clone https://github.com/houko/mac_config.git &&
      ln -sf ~/.xiaomo/share/github/mac_config ~/.xiaomo/mac_config &&
      ln -sf ~/.xiaomo/mac_config/bashrc ~/.bashrc &&
      ln -sf ~/.xiaomo/mac_config/gitconfig ~/.gitconfig &&
      ln -sf ~/.xiaomo/mac_config/inputrc.sh ~/.inputrc &&
      ln -sf ~/.xiaomo/mac_config/pythonrc.py ~/.pythonrc &&
      ln -sf ~/.xiaomo/mac_config/ptpython ~/.ptpython &&
      ln -sf ~/.xiaomo/mac_config/vim ~/.vim &&
      mkdir -p ~/.vim/backup &&
      ln -sf ~/.xiaomo/mac_config/vim ~/.config/nvim &&
      ln -sf ~/.xiaomo/mac_config/vim/init.vim ~/.vimrc &&
      ln -sf ~/.xiaomo/share/github ~/.GITHUB &&
      cd ~/.xiaomo/mac_config/go && go build -o ../bin/my_prompt my_prompt.go
    else
      cd ~/.xiaomo/mac_config && git pull
    fi
    curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    nvim -c "PlugUpdate" -c ":q!" -c ":q!" > /dev/null
    mkdir -p ~/.xiaomo/alt/mac_config && echo -n "export COLOR_LAST_GOOD=51\nexport COLOR_LAST_FAIL=199\nexport BASH_COMPLETION_DIR=/usr/share/bash-completion/completions" > ~/.xiaomo/alt/mac_config/bashrc
    echo "Done with User setup. Happy Hacking!"
  SCRIPT

  config.vm.provision "shell", privileged: false, inline: $user_script

end
